---
title: "Your DECIDE newsletter"
output: blastula::blastula_email
params:
  name: NULL
  email: NULL
  irecord_username: NA
  ispot_username: NA
  inat_username: NA
  ispot_key: NA
  irecord_key: NA
  data_stories: "all"
  randomise: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../functions/get_records.R")
source("../functions/get_data.R")
source("../functions/get_decide_score.R")
source("../functions/encode_graphic.R")
library(ggplot2)
library(dplyr)
library(htmltools)
library(curl)
library(jsonlite)
library(httr)
library(knitr)
library(RCurl)

```

<div>
```{r,echo=FALSE}
h1(paste("Hello",params$name))

p(paste("Date:",Sys.Date()))

h3("About you")
```

This is what we know about you: 

Your email is `r params$email`

Your iRecord username is `r params$irecord_username`

Your iSpot username is `r params$ispot_username`

Your iNaturalist username is `r params$inat_username`

</div>

```{r get records from websites, echo = F,warning=FALSE}

#create an empty dataframe with the corresponding headings
all_records <- data.frame(
  scientific_name = "  ",
  latitude = 0,
  longitude = 0,
  observed_on = "",
  url = "",
  image_url = "",
  confirmed = FALSE,
  website = ""
)[-1,]

#get records from iRecord
if (!is.na(params$irecord_username)){
  #key <- readLines(file("../.secrets/irecord_key.txt",open="r"))
  irecord_records <- get_records_irecord(params$irecord_username,nrecords = 10,params$irecord_key)
  irecord_records$website <- "iRecord"
  
  all_records <- bind_rows(all_records,irecord_records)
}

#get records from iSpot
if (!is.na(params$ispot_username)){
  #key <- readLines(file("../.secrets/ispot_key.txt",open="r"))
  ispot_records <- get_records_ispot(params$ispot_username,nrecords = 10,params$ispot_key)
  ispot_records$website <- "iSpot"
  
  all_records <- bind_rows(all_records,ispot_records)
}

#get records from iNaturalist
if (!is.na(params$inat_username)){
  inat_records <- get_records_inat(params$inat_username,nrecords = 10)
  inat_records$website <- "iNaturalist"
  
  all_records <- bind_rows(all_records,inat_records)
}

```

```{r data cleaning, echo = FALSE,warning=FALSE,error=FALSE}

if(nrow(all_records)== 0){
  stop("Error: couldn't get any records for the provided usernames")
}

all_records$observed_on <- all_records$observed_on %>% as.Date()

#remove ones with NA date
all_records <- all_records %>% filter(!is.na(observed_on))

#identify butterflies vs moths
all_records$name <- "butterfly" #dummy


#detect and remove duplicates


#group into visits


```

```{r get decide score, echo = F}

# get decide score
all_records$decide_score <- apply(all_records[,c("latitude","longitude","name")],1, function(x) {get_decide_score(x[1],x[2],x[3])})

#unlist it but preserve null values
all_records$decide_score[sapply(all_records$decide_score, is.null)] <- NA
all_records$decide_score <- unlist(all_records$decide_score)

```

```{r highlight dataframes, echo = F}
#some highlights that are used in the visualisation:
best_record <- all_records %>% arrange(desc(decide_score)) %>% head(n=1)
most_recent_record <- all_records %>% arrange(desc(observed_on)) %>% head(n=1)
```

```{r data stories, echo=FALSE,warning = F}
#this is where we define functions that use variables from the global environment (don't have any arguments) that output one HTML div which contains all the content
#functions are prefixed with `ds_` (data stories)

#table of records
ds_table_of_records <- function(){
  div(
    id = "table of records",
    class = "data-story",
    
    h3("Your recent records"),
    HTML(kable(all_records[,c("scientific_name","latitude","longitude","observed_on","name","website","decide_score")],"html"))
  )
}


#your most valuable record:
ds_most_valuable_record <- function(){
  
  div(
    id = "most-valuable-record",
    class="data-story",
    
    h3("Your most valuable record"),
    img(src = best_record$image_url),
    p("Your most valuable record is a record of ",
      em(best_record$scientific_name),
      " observed on ",
      best_record$observed_on,
      " with a DECIDE recording priority value of ",
      best_record$decide_score,
      ". Wow! Why not make more records in this area?",
      a("Visit the DECIDE recorder tool",
        href="https://decide.ceh.ac.uk/opts/scoremap/map",
        target="_blank"))
  )
}


#recording timeline
ds_timeline <- function(){
  #generate some language (not very naturally)
  if (most_recent_record$decide_score > mean(all_records$decide_score,na.rm = T)){
    recent_verses_average <- "was above your average recording priority. Nice one!"
  } else {
    recent_verses_average <- "was below your average recording priority."
  }
  
  #produce the graphic for the 
  g <- all_records %>% ggplot(aes(x = observed_on,y = decide_score,label = scientific_name))+
    geom_point()+
    scale_x_date()+
    theme_bw()+
    labs(x = "Date of record",y = "DECIDE recording priority")
  
  #encoded graphic
  enc_g <- encode_graphic(g)
    
  
  #build element
  div(
    id = "recording_timeline",
    class = "data-story",
    
    h3("Your recording timeline"),
    p("Have been recording more strategically recently? Let\'s have a look!"),
    HTML(enc_g),
    p("You most recent record of",
      most_recent_record$scientific_name,
      recent_verses_average,
      a("Visit the DECIDE recorder tool",
        href="https://decide.ceh.ac.uk/opts/scoremap/map",
        target="_blank")
    )
  )
}

```

```{r produce data stories, results='asis',echo=FALSE,warning=FALSE}

# get the available functions (with the ds_ prefix)
available_data_stories <- lsf.str() %>% as.vector()
available_data_stories <- available_data_stories[available_data_stories %>% startsWith("ds_")]

params$data_stories <- strsplit(params$data_stories,",")

# workout whether to run some or all of the data stories  
# if the markdown has been selected to render with all data stories th
if(params$data_stories == "all"){
    data_stories <- available_data_stories
  } else {
    #otherwise, first check to see if all the functions specified in the params$data_stories have actually got corresponding functions loaded into the environment
  if (!(FALSE %in% (data_stories %in% params$data_stories))){
    data_stories <- params$data_stories
  } else {
    # if there aren't available functions then display a error message to stop the render
    stop(paste("You have specified a data story in the markdown parameters but there is no corresponding function. You specified these data stories:\n ",params$data_stories, "\nbut these are the functions available:\n ",paste(data_stories,collapse = "\n  ")))
  }
}

#the data stories will be generated in the order specified in the markdown parameters if randomise if set to FALSE (default). if it is set to TRUE then randomise the data stories using `sample()`

#note that if params$data_stoies = "all" then the data stories will be rendered in alphabetical order of the function names
if(params$randomise){
  data_stories <- sample(data_stories)
}

#go through the data stories and run the function for each using `do.call`
for (story in data_stories){
  rendered_story <- do.call(story,args = list())
  print(rendered_story)
}

```

<hr>

<div>
This newsletter was generated on `r Sys.time()`

Don\'t want to receive these emails any more? <a>Unsubscribe from the DECIDE personalised newsletter</a>
</div>





